#!/bin/sh

WINESOURCE=$(pwd)/wine-pure

mkdir -p include/

# from wine, needed for windows.h
# edited winbase.h winnt.h
for i in windows.h excpt.h windef.h   basetsd.h guiddef.h \
         "pshpack?.h" poppack.h winnt.rh    winerror.h \
         libloaderapi.h winuser.h winuser.rh winnls.h wincon.h \
         winver.h verrsrc.h winreg.h \
         reason.h winnetwk.h cderr.h dde.h dde.rh ddeml.h \
         lzexpand.h winperf.h strsafe.h; do
    # TODO: add comment do not change this code
    cp -f $WINESOURCE/include/$i include/
done

# from wine, internal
for i in winternl.h ntdef.h ntstatus.h ; do
    # TODO: add comment do not change this code
    cp -f $WINESOURCE/include/$i include/
done

# from include/wine
mkdir -p include/wine/
for i in port.h exception.h unicode.h debug.h \
         list.h library.h rbtree.h; do
    # TODO: add comment do not change this code
    cp -f $WINESOURCE/include/wine/$i include/wine/
done

# from include/ddk
mkdir -p include/ddk/
for i in ntddk.h wdm.h; do
    # TODO: add comment do not change this code
    cp -f $WINESOURCE/include/ddk/$i include/ddk/
done


# from wine, needed for build libs
for i in winioctl.h fileapi.h inaddr.h in6addr.h; do
    # TODO: add comment do not change this code
    cp -f $WINESOURCE/include/$i include/
done

# modified at our side
mkdir -p include.otowi/wine/
for i in config.h wingdi.h port.h wine/server.h winbase.h winnt.h; do
    rm -f include/$i
    ln -sr include.otowi/$i include/$i
done

create_stub()
{
#mkdir -p "$(dirname "$1")"
local UP=$(basename "$1" | tr [:lower:] [:upper:] | sed -e "s|\.|_|g")
cat <<EOF > "$1"
/* Autogenerated with $0. 
   Remove from $0 if you wish add edited version of this.
 */
#ifndef __WINE_$UP
#define __WINE_$UP

/* Stub header. */

#endif  /* #ifdef __WINE_UP_H */
EOF
}

# just stub
for i in dlgs.h mmsystem.h nb30.h rpc.h shellapi.h \
    winsock.h wincrypt.h winscard.h winsvc.h mcx.h imm.h \
    imm.h ; do
    create_stub include.otowi/$i
    rm -f include/$i
    ln -sr include.otowi/$i include/$i
done


# copy port code
mkdir -p src/port/codepages/
for i in "c_*.c" ; do
    # TODO: add comment do not change this code
    cp -f $WINESOURCE/libs/port/$i src/port/codepages/
done

# TODO: copy all
for i in compose.c cpsymbol.c cptable.c  decompose.c mbtowc.c utf8.c wctomb.c ; do
    # TODO: add comment do not change this code
    cp -f $WINESOURCE/libs/port/$i src/port/
done

for i in casemap.c collation.c debug.c sortkey.c wctype.c mmap.c string.c; do
    # TODO: add comment do not change this code
    cp -f $WINESOURCE/libs/wine/$i src/port/
done
