/* Autogenerated with ./update_from_wine.sh. 
   Remove from ./update_from_wine.sh if you wish add edited version of this.
 */
#ifndef __WINE_SERVER_H
#define __WINE_SERVER_H

// from server_protocol.h
typedef unsigned int obj_handle_t;

#define DUP_HANDLE_CLOSE_SOURCE  DUPLICATE_CLOSE_SOURCE
#define DUP_HANDLE_SAME_ACCESS   DUPLICATE_SAME_ACCESS
#define DUP_HANDLE_MAKE_GLOBAL   0x80000000

typedef __int64 timeout_t;
#define TIMEOUT_INFINITE (((timeout_t)0x7fffffff) << 32 | 0xffffffff)

#endif  /* #ifdef __WINE_UP_H */
