/* Autogenerated with ./update_from_wine.sh. 
   Remove from ./update_from_wine.sh if you wish add edited version of this.
 */
#ifndef __WINE_WINCRYPT_H
#define __WINE_WINCRYPT_H

/* Stub header. */

#endif  /* #ifdef __WINE_UP_H */
